/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellTerminalsRouteImport } from './routes/_shell.terminals'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellHostHostIdSessionSessionIdRouteImport } from './routes/_shell.host.$hostId.session.$sessionId'
import { Route as ShellHostHostIdProjectProjectIdRouteImport } from './routes/_shell.host.$hostId.project.$projectId'
import { Route as ShellHostHostIdProjectProjectIdSettingsRouteImport } from './routes/_shell.host.$hostId.project.$projectId_.settings'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTerminalsRoute = ShellTerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHostHostIdSessionSessionIdRoute =
  ShellHostHostIdSessionSessionIdRouteImport.update({
    id: '/host/$hostId/session/$sessionId',
    path: '/host/$hostId/session/$sessionId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellHostHostIdProjectProjectIdRoute =
  ShellHostHostIdProjectProjectIdRouteImport.update({
    id: '/host/$hostId/project/$projectId',
    path: '/host/$hostId/project/$projectId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellHostHostIdProjectProjectIdSettingsRoute =
  ShellHostHostIdProjectProjectIdSettingsRouteImport.update({
    id: '/host/$hostId/project/$projectId_/settings',
    path: '/host/$hostId/project/$projectId/settings',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/settings': typeof ShellSettingsRoute
  '/terminals': typeof ShellTerminalsRoute
  '/host/$hostId/project/$projectId': typeof ShellHostHostIdProjectProjectIdRoute
  '/host/$hostId/session/$sessionId': typeof ShellHostHostIdSessionSessionIdRoute
  '/host/$hostId/project/$projectId/settings': typeof ShellHostHostIdProjectProjectIdSettingsRoute
}
export interface FileRoutesByTo {
  '/settings': typeof ShellSettingsRoute
  '/terminals': typeof ShellTerminalsRoute
  '/': typeof ShellIndexRoute
  '/host/$hostId/project/$projectId': typeof ShellHostHostIdProjectProjectIdRoute
  '/host/$hostId/session/$sessionId': typeof ShellHostHostIdSessionSessionIdRoute
  '/host/$hostId/project/$projectId/settings': typeof ShellHostHostIdProjectProjectIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/terminals': typeof ShellTerminalsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/host/$hostId/project/$projectId': typeof ShellHostHostIdProjectProjectIdRoute
  '/_shell/host/$hostId/session/$sessionId': typeof ShellHostHostIdSessionSessionIdRoute
  '/_shell/host/$hostId/project/$projectId_/settings': typeof ShellHostHostIdProjectProjectIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/terminals'
    | '/host/$hostId/project/$projectId'
    | '/host/$hostId/session/$sessionId'
    | '/host/$hostId/project/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/terminals'
    | '/'
    | '/host/$hostId/project/$projectId'
    | '/host/$hostId/session/$sessionId'
    | '/host/$hostId/project/$projectId/settings'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/settings'
    | '/_shell/terminals'
    | '/_shell/'
    | '/_shell/host/$hostId/project/$projectId'
    | '/_shell/host/$hostId/session/$sessionId'
    | '/_shell/host/$hostId/project/$projectId_/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/terminals': {
      id: '/_shell/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof ShellTerminalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/host/$hostId/session/$sessionId': {
      id: '/_shell/host/$hostId/session/$sessionId'
      path: '/host/$hostId/session/$sessionId'
      fullPath: '/host/$hostId/session/$sessionId'
      preLoaderRoute: typeof ShellHostHostIdSessionSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/host/$hostId/project/$projectId': {
      id: '/_shell/host/$hostId/project/$projectId'
      path: '/host/$hostId/project/$projectId'
      fullPath: '/host/$hostId/project/$projectId'
      preLoaderRoute: typeof ShellHostHostIdProjectProjectIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/host/$hostId/project/$projectId_/settings': {
      id: '/_shell/host/$hostId/project/$projectId_/settings'
      path: '/host/$hostId/project/$projectId/settings'
      fullPath: '/host/$hostId/project/$projectId/settings'
      preLoaderRoute: typeof ShellHostHostIdProjectProjectIdSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTerminalsRoute: typeof ShellTerminalsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellHostHostIdProjectProjectIdRoute: typeof ShellHostHostIdProjectProjectIdRoute
  ShellHostHostIdSessionSessionIdRoute: typeof ShellHostHostIdSessionSessionIdRoute
  ShellHostHostIdProjectProjectIdSettingsRoute: typeof ShellHostHostIdProjectProjectIdSettingsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTerminalsRoute: ShellTerminalsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellHostHostIdProjectProjectIdRoute: ShellHostHostIdProjectProjectIdRoute,
  ShellHostHostIdSessionSessionIdRoute: ShellHostHostIdSessionSessionIdRoute,
  ShellHostHostIdProjectProjectIdSettingsRoute:
    ShellHostHostIdProjectProjectIdSettingsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
